version: "3.9"
services:
  boleto_solar_postgres:
    image: postgres
    platform: linux/amd64
    container_name: boleto_solar_postgres
    environment:
      POSTGRES_PASSWORD: boleto_solar
      POSTGRES_HOST_AUTH_METHOD: trust
      HOST: http://192.168.0.107:3000
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data:z

  boleto_solar:
    build: .
    platform: linux/amd64
    container_name: boleto_solar
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/var/www/boleto_solar:z
    ports:
      - "3000:3000"
    depends_on:
      - boleto_solar_postgres

# docker compose build
# docker compose run --rm boleto_solar bundle install
# docker compose run --rm boleto_solar rake db:drop
# docker compose run --rm boleto_solar rake db:create
# docker compose run --rm boleto_solar rake db:migrate
# docker compose run --rm boleto_solar rake seed:migrate
# docker compose run  --rm -p 3000:3000 boleto_solar rails s -b 0.0.0.0
# docker compose run  --rm boleto_solar rails c